# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a5f427d47f6a12f4a2e77785b18fbc8995513148013eec1dfb0c3010a068ee43e4e0136fe655c4806ed379b533846cf15bf77880ce63a2b4b268f9f2c613ace

test:
  secret_key_base: d7a9ce6802cf8d0d2977dad201988aa548d0105233976fc4363c17e5f17dfc615f74569396112d54c947d1fec15e438c25c7a7040c3d30dec4521ff37f1577c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
